# Generated by Django 5.1.1 on 2025-01-09 03:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Make",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Car's make (e.g. Ford)",
                        max_length=200,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                2, "Make must be at least 2 characters long"
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Auto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        help_text="Car's nickname (e.g. Focus)",
                        max_length=200,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                2, "Nickname must be at least 2 characters long"
                            )
                        ],
                    ),
                ),
                ("mileage", models.IntegerField()),
                ("comments", models.TextField(blank=True, max_length=300)),
                (
                    "make",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="autos.make"
                    ),
                ),
            ],
        ),
    ]
