# Generated by Django 5.1.1 on 2024-10-30 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auto",
            name="nickname",
            field=models.CharField(
                help_text="Car's nickname (e.g. Focus)",
                max_length=200,
                validators=[
                    django.core.validators.MinLengthValidator(
                        2, "Nickname must be at least 2 characters long"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="make",
            name="name",
            field=models.CharField(
                help_text="Car's make (e.g. Ford)",
                max_length=200,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        2, "Make must be at least 2 characters long"
                    )
                ],
            ),
        ),
    ]
