# Generated by Django 5.1.1 on 2024-10-31 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breed",
            name="name",
            field=models.CharField(
                max_length=200,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        2, "Breed must be at least 2 characters long"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="cat",
            name="nickname",
            field=models.CharField(
                max_length=200,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        2, "Nickname must be at least 2 characters long"
                    )
                ],
            ),
        ),
    ]
