# Generated by Django 5.1.1 on 2025-01-09 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=200)),
                (
                    "pub_date",
                    models.DateTimeField(
                        verbose_name="Date the poll is available for voting."
                    ),
                ),
                (
                    "exp_date",
                    models.DateTimeField(
                        verbose_name="Date the poll is closed for voting."
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["pub_date"], name="polls_quest_pub_dat_5d0c19_idx"
                    ),
                    models.Index(
                        fields=["exp_date"], name="polls_quest_exp_dat_00aff6_idx"
                    ),
                    models.Index(
                        fields=["pub_date", "exp_date"],
                        name="polls_quest_pub_dat_5ec920_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice_text", models.CharField(max_length=200)),
                ("votes", models.IntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        related_query_name="choice",
                        to="polls.question",
                    ),
                ),
            ],
        ),
    ]
