# Generated by Django 5.1.1 on 2024-10-08 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_alter_question_pub_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="exp_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 7, 8, 47, 42, 965195, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date the poll is closed for voting.",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="pub_date",
            field=models.DateTimeField(
                verbose_name="Date the poll is available for voting."
            ),
        ),
    ]
