# Generated by Django 5.1.1 on 2024-10-08 10:21

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_question_exp_date_alter_question_pub_date"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="question",
            managers=[
                ("polls", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["pub_date"], name="polls_quest_pub_dat_5d0c19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["exp_date"], name="polls_quest_exp_dat_00aff6_idx"
            ),
        ),
    ]
