# Generated by Django 5.1.1 on 2024-10-09 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0005_question_polls_quest_pub_dat_5ec920_idx"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["-pub_date"]},
        ),
        migrations.AlterModelManagers(
            name="question",
            managers=[],
        ),
    ]
