# Generated by Django 5.1.1 on 2024-10-25 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0006_alter_question_options_alter_question_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={},
        ),
    ]
