# Generated by Django 5.1.1 on 2025-02-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="home/static/home/images/projects"
            ),
        ),
    ]
