# Generated by Django 5.1.1 on 2025-02-18 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_project_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["status", "-updated_at", "-created_at"]},
        ),
    ]
