# Generated by Django 5.1.1 on 2025-02-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_project_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-status", "-updated_at", "-created_at"]},
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[("Development", 1), ("Beta", 2), ("Live", 3)], max_length=20
            ),
        ),
    ]
