# Generated by Django 5.1.1 on 2025-02-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_alter_project_options_alter_project_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[(1, "Development"), (2, "Beta"), (3, "Live")], max_length=20
            ),
        ),
    ]
