# Generated by Django 5.1.1 on 2025-02-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_alter_project_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("Development", "Development"),
                    ("Beta", "Beta"),
                    ("Live", "Live"),
                ],
                max_length=20,
            ),
        ),
    ]
