# Generated by Django 5.1.1 on 2025-02-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_alter_project_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["status", "-updated_at", "-created_at"]},
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("Live", "Live"),
                    ("Beta", "Beta"),
                    ("Development", "Development"),
                ],
                max_length=20,
            ),
        ),
    ]
