# Generated by Django 5.1.1 on 2025-01-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_alter_advertisement_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="text",
            field=models.TextField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="historicaladvertisement",
            name="text",
            field=models.TextField(default="", null=True),
        ),
    ]
