# Generated by Django 5.1.1 on 2025-01-09 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0004_alter_advertisement_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advertisement",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="historicaladvertisement",
            name="updated_at",
        ),
    ]
