# Generated by Django 5.1.1 on 2025-01-29 07:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0006_advertisement_updated_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Advertisement",
            new_name="Ad",
        ),
        migrations.RenameModel(
            old_name="HistoricalAdvertisement",
            new_name="HistoricalAd",
        ),
        migrations.AlterModelOptions(
            name="historicalad",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical ad",
                "verbose_name_plural": "historical ads",
            },
        ),
    ]
