# Generated by Django 5.1.1 on 2025-02-19 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0008_alter_ad_created_at_alter_ad_owner_alter_ad_price_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Comment for your advertisement",
                        verbose_name="Comment",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the comment was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "ad",
                    models.ForeignKey(
                        help_text="Ad that this comment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ads.ad",
                        verbose_name="Ad",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="User that created the comment",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ad",
            name="comments",
            field=models.ManyToManyField(
                blank=True,
                help_text="Comments for your advertisement",
                related_name="ads",
                to="ads.adcomment",
                verbose_name="Comments",
            ),
        ),
    ]
