# Generated by Django 5.1.1 on 2025-02-19 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0009_adcomment_ad_comments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ad",
            name="comments",
        ),
    ]
