# Generated by Django 5.1.1 on 2025-02-19 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0010_remove_ad_comments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="adcomment",
            name="ad",
            field=models.ForeignKey(
                help_text="Ad that this comment belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                related_query_name="comment",
                to="ads.ad",
                verbose_name="Ad",
            ),
        ),
        migrations.AlterField(
            model_name="adcomment",
            name="author",
            field=models.ForeignKey(
                help_text="User that created the comment",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                related_query_name="comment",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
    ]
