# Generated by Django 5.1.1 on 2025-02-19 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0011_alter_adcomment_ad_alter_adcomment_author"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="adcomment",
            name="author",
            field=models.ForeignKey(
                help_text="User that created the comment",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                related_query_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
    ]
