# Generated by Django 5.1.1 on 2025-02-19 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0013_alter_adcomment_author"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="adcomment",
            name="author",
            field=models.ForeignKey(
                help_text="User that created the comment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.CreateModel(
            name="AdImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Image for your advertisement",
                        null=True,
                        upload_to="ads",
                        verbose_name="Image",
                    ),
                ),
                (
                    "ad",
                    models.ForeignKey(
                        help_text="Ad that this image belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        related_query_name="image",
                        to="ads.ad",
                        verbose_name="Ad",
                    ),
                ),
            ],
        ),
    ]
