# Generated by Django 5.1.1 on 2025-02-19 03:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0014_alter_adcomment_author_adimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="adimage",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="When the image was uploaded",
                verbose_name="Created at",
            ),
            preserve_default=False,
        ),
    ]
