# Generated by Django 5.1.1 on 2025-02-20 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0015_adimage_uploaded_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ad",
            old_name="owner",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="historicalad",
            old_name="owner",
            new_name="author",
        ),
        migrations.AlterField(
            model_name="adcomment",
            name="text",
            field=models.TextField(
                help_text="Comment for your advertisement",
                validators=[
                    django.core.validators.MinLengthValidator(
                        3, "Comment must be at least 3 characters long"
                    )
                ],
                verbose_name="Comment",
            ),
        ),
        migrations.AlterField(
            model_name="adimage",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Image for your advertisement",
                null=True,
                upload_to="ads",
                validators=[
                    django.core.validators.MaxLengthValidator(
                        2097152, "Image must be less than 2 MB"
                    )
                ],
                verbose_name="Image",
            ),
        ),
    ]
