# Generated by Django 5.1.1 on 2025-02-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0016_rename_owner_ad_author_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adcomment",
            options={"ordering": ["-created_at"]},
        ),
    ]
