# Generated by Django 5.1.1 on 2025-02-20 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0017_alter_adcomment_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adcomment",
            name="text",
            field=models.TextField(
                help_text="Comment for your advertisement",
                validators=[
                    django.core.validators.MinLengthValidator(
                        2, "Comment must be at least 2 characters long"
                    )
                ],
                verbose_name="Comment",
            ),
        ),
    ]
