# Generated by Django 5.1.1 on 2025-02-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0018_alter_adcomment_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="adcomment",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Last time the comment was updated",
                null=True,
                verbose_name="Updated at",
            ),
        ),
    ]
