# Generated by Django 5.1.1 on 2025-02-20 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0020_alter_adcomment_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adcomment",
            name="updated_at",
        ),
    ]
