# Generated by Django 5.1.1 on 2025-02-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_squashed_0021_remove_adcomment_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adimage",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="When the image was uploaded",
                verbose_name="Created at",
            ),
        ),
    ]
