# Generated by Django 5.1.6 on 2025-02-21 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0022_alter_adimage_uploaded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="adcomment",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Image for your advertisement",
                null=True,
                upload_to="ads",
                validators=[
                    django.core.validators.MaxLengthValidator(
                        2097152, "Image must be less than 2.00 MB MB"
                    )
                ],
                verbose_name="Image",
            ),
        ),
        migrations.DeleteModel(
            name="AdImage",
        ),
    ]
