# Generated by Django 5.1.6 on 2025-02-22 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0026_alter_ad_image_alter_historicalad_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ad",
            old_name="image",
            new_name="picture",
        ),
        migrations.RenameField(
            model_name="historicalad",
            old_name="image",
            new_name="picture",
        ),
    ]
