# Generated by Django 5.1.6 on 2025-02-24 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0027_rename_image_ad_picture_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ad",
                    models.ForeignKey(
                        help_text="Ad that this favorite belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        related_query_name="favorite",
                        to="ads.ad",
                        verbose_name="Ad",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User that created the favorite",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ad",
            name="favored_by",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users that favorited the advertisement",
                related_name="favorite_ads",
                through="ads.AdFavorite",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Favored by",
            ),
        ),
    ]
