# Generated by Django 5.1.6 on 2025-02-24 09:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0028_adfavorite_ad_favored_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="adfavorite",
            unique_together={("ad", "user")},
        ),
    ]
