# Generated by Django 5.1.6 on 2025-02-24 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0029_alter_adfavorite_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="adfavorite",
            name="ad",
            field=models.ForeignKey(
                help_text="Ad that this favorite belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                related_query_name="+",
                to="ads.ad",
                verbose_name="Ad",
            ),
        ),
        migrations.AlterField(
            model_name="adfavorite",
            name="user",
            field=models.ForeignKey(
                help_text="User that created the favorite",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
    ]
