# Generated by Django 5.1.6 on 2025-02-24 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0030_alter_adfavorite_ad_alter_adfavorite_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="favored_by",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users that favorited the advertisement",
                related_name="favorite_ads",
                related_query_name="favorite_ad",
                through="ads.AdFavorite",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Favored by",
            ),
        ),
    ]
