# Generated by Django 5.1.6 on 2025-02-25 19:41

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0031_alter_ad_favored_by"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
