# Generated by Django 5.1.1 on 2025-02-01 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("short_url", "0004_alter_historicalshorturl_url_alter_shorturl_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalshorturl",
            name="url",
            field=models.URLField(
                validators=[
                    django.core.validators.MinLengthValidator(
                        3, "URL must be at least 3 characters long"
                    )
                ],
                verbose_name="URL",
            ),
        ),
        migrations.AlterField(
            model_name="shorturl",
            name="url",
            field=models.URLField(
                validators=[
                    django.core.validators.MinLengthValidator(
                        3, "URL must be at least 3 characters long"
                    )
                ],
                verbose_name="URL",
            ),
        ),
    ]
